USE [master]
GO

/****** Object:  Database [SUSHI_X]    Script Date: 12/27/2024 8:23:38 PM ******/
CREATE DATABASE [SUSHI_X]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SUSHI_X', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SUSHI_X.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SUSHI_X_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SUSHI_X_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SUSHI_X].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SUSHI_X] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SUSHI_X] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SUSHI_X] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SUSHI_X] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SUSHI_X] SET ARITHABORT OFF 
GO

ALTER DATABASE [SUSHI_X] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SUSHI_X] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SUSHI_X] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SUSHI_X] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SUSHI_X] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SUSHI_X] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SUSHI_X] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SUSHI_X] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SUSHI_X] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SUSHI_X] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SUSHI_X] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SUSHI_X] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SUSHI_X] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SUSHI_X] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SUSHI_X] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SUSHI_X] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SUSHI_X] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SUSHI_X] SET RECOVERY FULL 
GO

ALTER DATABASE [SUSHI_X] SET  MULTI_USER 
GO

ALTER DATABASE [SUSHI_X] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SUSHI_X] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SUSHI_X] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SUSHI_X] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SUSHI_X] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SUSHI_X] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SUSHI_X] SET QUERY_STORE = ON
GO

ALTER DATABASE [SUSHI_X] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SUSHI_X] SET  READ_WRITE 
GO


