USE SUSHI_X;
GO

INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_d048bceb', 'CAT_SUSHI', N'Salmon Nigiri', 35000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_1d7d641f', 'CAT_SUSHI', N'Tuna Nigiri', 40000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_c5f7580e', 'CAT_SUSHI', N'Ebi Nigiri', 35000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_739c1d92', 'CAT_SUSHI', N'Unagi Nigiri', 45000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_c6eea35b', 'CAT_SUSHI', N'Tamago Nigiri', 30000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_bdc31f96', 'CAT_SUSHI', N'Ikura Gunkan', 50000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_8571544c', 'CAT_SUSHI', N'Tobiko Gunkan', 45000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_58194db2', 'CAT_SASHIMI', N'Salmon Sashimi (5 pcs)', 120000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_b78f68a3', 'CAT_SASHIMI', N'Tuna Sashimi (5 pcs)', 130000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_bea8bc4f', 'CAT_SASHIMI', N'Mixed Sashimi Platter', 250000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_bfea8094', 'CAT_SASHIMI', N'Premium Sashimi Set', 350000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_c287805e', 'CAT_SASHIMI', N'Yellowtail Sashimi', 150000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_d7a5bad9', 'CAT_MAKI', N'California Roll', 85000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_d8cf52d5', 'CAT_MAKI', N'Spicy Tuna Roll', 95000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_0c7841fd', 'CAT_MAKI', N'Dragon Roll', 120000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_a224692b', 'CAT_MAKI', N'Rainbow Roll', 130000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_59f5385d', 'CAT_MAKI', N'Philadelphia Roll', 110000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_f00ebd3a', 'CAT_MAKI', N'Avocado Roll', 75000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_fd5b9e45', 'CAT_MAKI', N'Cucumber Roll', 65000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_d2a666ef', 'CAT_TEMAKI', N'Salmon Temaki', 55000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_8ef65730', 'CAT_TEMAKI', N'Spicy Tuna Temaki', 60000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_4e03e0d9', 'CAT_TEMAKI', N'California Temaki', 55000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_aba04884', 'CAT_TEMAKI', N'Unagi Temaki', 65000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_6fc85551', 'CAT_APPETIZER', N'Edamame', 45000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_647b9d51', 'CAT_APPETIZER', N'Gyoza (6 pcs)', 65000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_8dab109e', 'CAT_APPETIZER', N'Tempura Moriawase', 95000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_169fb7c9', 'CAT_APPETIZER', N'Agedashi Tofu', 55000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_b7468520', 'CAT_APPETIZER', N'Takoyaki (6 pcs)', 75000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_00cfed34', 'CAT_APPETIZER', N'Miso Soup', 30000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_004d3c0e', 'CAT_SOUP', N'Shoyu Ramen', 95000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_3947f389', 'CAT_SOUP', N'Miso Ramen', 95000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_845699f9', 'CAT_SOUP', N'Udon Noodle Soup', 85000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_4654de52', 'CAT_SOUP', N'Tempura Udon', 105000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_8f8cb4dd', 'CAT_SOUP', N'Nabeyaki Udon', 115000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_a491d140', 'CAT_BENTO', N'Salmon Teriyaki Bento', 150000, 0);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_84668db3', 'CAT_BENTO', N'Chicken Katsu Bento', 135000, 0);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_e73f4dc3', 'CAT_BENTO', N'Tempura Bento', 140000, 0);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_8cee9b43', 'CAT_BENTO', N'Unagi Bento', 180000, 0);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_26d03602', 'CAT_BENTO', N'Vegetarian Bento', 120000, 0);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_a21a7d20', 'CAT_DRINKS', N'Green Tea', 25000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_9060c740', 'CAT_DRINKS', N'Sake (Small)', 85000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_5cc38e2f', 'CAT_DRINKS', N'Sake (Large)', 150000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_955f6099', 'CAT_DRINKS', N'Asahi Beer', 45000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_cfb4c74a', 'CAT_DRINKS', N'Sapporo Beer', 45000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_155ddac9', 'CAT_DRINKS', N'Soft Drinks', 25000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_b7c989d4', 'CAT_DRINKS', N'Japanese Soda', 35000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_ef9e2431', 'CAT_DRINKS', N'Mineral Water', 20000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_9bdcb438', 'CAT_DESSERT', N'Mochi Ice Cream (3 pcs)', 45000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_9d1bd558', 'CAT_DESSERT', N'Green Tea Ice Cream', 35000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_9d79ad84', 'CAT_DESSERT', N'Tempura Ice Cream', 55000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_fe5c5e92', 'CAT_DESSERT', N'Dorayaki', 40000, 1);
INSERT INTO MENU_ITEM (ItemID, CategoryID, ItemName, CurrentPrice, DeliveryAvailable) VALUES ('ITEM_d4ecd640', 'CAT_DESSERT', N'Matcha Pudding', 45000, 1);
